[package]
name = "fenwick-binary-indexed-tree"
version = "0.1.0"
authors = ["f8122dac91 <f8122dac91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
